name: flutter_progressed_play_button
description: A simple Flutter widget that presents a "play button" with a progress drawn as an arc around the icon.
version: 0.2.0
homepage: https://github.com/zonble/flutter_progressed_play_button

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

flutter:

screenshots:
  - description: "The states of the button."
    path: buttons.png
