name: flutter_progressed_play_button
description: A simple Flutter widget that presents a "play button" with a progress drawn as an arc around the icon.
version: 0.1.3
homepage: https://github.com/zonble/flutter_progressed_play_button

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic: ^1.9.2

flutter:
