name: Flutter Web

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: "17"
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.32.0"
          channel: "stable"
      - name: Upgrades flutter
        run: flutter upgrade
        working-directory: ./example
      - name: Enable Web
        run: flutter config --enable-web
        working-directory: ./example
      - name: Install dependencies
        run: flutter packages get
        working-directory: ./example
      - name: Build Web
        run: flutter build web
        working-directory: ./example
      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: example/build/web # The folder the action should deploy.

